<a href="https://colab.research.google.com/github/brezinskieduarda/cypress/blob/main/estudo_pandas_colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd

In [ ]:
pd.show_versions()

INSTALLED VERSIONS
------------------
commit                : d9cdd2ee5a58015ef6f4d15c7226110c9aab8140
python                : 3.12.13.final.0
python-bits           : 64
OS                    : Linux
OS-release            : 6.6.122+
Version               : #1 SMP Thu Apr 30 18:17:14 UTC 2026
machine               : x86_64
processor             : x86_64
byteorder             : little
LC_ALL                : en_US.UTF-8
LANG                  : en_US.UTF-8
LOCALE                : en_US.UTF-8

pandas                : 2.2.2
numpy                 : 2.0.2
pytz                  : 2025.2
dateutil              : 2.9.0.post0
setuptools            : 75.2.0
pip                   : 24.1.2
Cython                : 3.0.12
pytest                : 8.4.2
hypothesis            : None
sphinx                : 8.2.3
blosc                 : None
feather               : None
xlsxwriter            : None
lxml.etree            : 6.1.1
html5lib              : 1.1
pymysql               : None
psycopg2              : 2.9.12
jinja2                : 3.1.6
IPython               : 7.34.0
pandas_datareader     : 0.10.0
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : 4.13.5
bottleneck            : 1.4.2
dataframe-api-compat  : None
fastparquet           : None
fsspec                : 2025.3.0
gcsfs                 : 2025.3.0
matplotlib            : 3.10.0
numba                 : 0.60.0
numexpr               : 2.14.1
odfpy                 : None
openpyxl              : 3.1.5
pandas_gbq            : 0.30.0
pyarrow               : 18.1.0
pyreadstat            : None
python-calamine       : None
pyxlsb                : None
s3fs                  : None
scipy                 : 1.16.3
sqlalchemy            : 2.0.50
tables                : 3.10.2
tabulate              : 0.9.0
xarray                : 2025.12.0
xlrd                  : 2.0.2
zstandard             : 0.25.0
tzdata                : 2026.2
qtpy                  : None
pyqt5                 : None

In [ ]:
import pandas as pd
serie_1 = pd.Series(data=[10,22,23,48,54], index=[1,1,2,3,4])
print(serie_1)

1    10
1    22
2    23
3    48
4    54
dtype: int64

In [ ]:
df =pd.read_csv('https://raw.githubusercontent.com/brunamulinari/BasicPythonProjects/main/Base_ficticia/baseficticia.csv',delimiter=';')

In [ ]:
df=pd.read_csv('https://raw.githubusercontent.com/brunamulinari/BasicPythonProjects/main/Base_ficticia/baseficticia.csv', delimiter=';')
df.head(5)

   id     data_aq produto  quantidade  valor UN      TotaL       setor
0   0  01/01/2019  toalha           6  R$ 35,00  R$ 210,00  Mesa_banho
1   1  02/01/2019  toalha           6  R$ 35,00  R$ 210,00          --
2   2  03/01/2019  toalha           2  R$ 35,00   R$ 70,00  mesa_banho
3   3  01/02/2019  toalha           5  R$ 35,00  R$ 175,00        nada
4   4  02/02/2019  toalha           9  R$ 35,00  R$ 315,00  mesa_banho

In [ ]:
df=pd.read_csv('https://www.harve.com.br/praticas/titanic-pt-BR.csv', delimiter=',')
df.head(5)

,Id do passageiro,Sobrevivente,Classe,Nome,Sexo,Idade,Irmaos ou conjuge,Pais ou filhos,Ticket,Tarifa do passageiro,Cabine,Local de embarque
0,1,0,3,"Braund, Mr. Owen Harris",masculino,22.0,1,0,A/5 21171,7.25,NaN,Southampton
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",feminino,38.0,1,0,PC 17599,712.833,C85,Cherbourg
2,3,1,3,"Heikkinen, Miss. Laina",feminino,26.0,0,0,STON/O2. 3101282,7.925,NaN,Southampton
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",feminino,35.0,1,0,113803,53.1,C123,Southampton
4,5,0,3,"Allen, Mr. William Henry",masculino,35.0,0,0,373450,08.05,NaN,Southampton

In [ ]:
df_titanic = pd.DataFrame([{'Id do passageiro': 892,'Sobrevivente': 0,'Classe': 1,'Nome': 'Cristiane','Sexo': 'feminino','Irmaos ou conjuge': 1,'Pais ou filhos': 1,'Local de embarque': 'Cherbourg','Ticket': '121A','Tarifa do passageiro': 8000,'Cabine': 'C85'}])
df = pd.concat([df, df_titanic], axis=0, ignore_index=True)
df_titanic

,Id do passageiro,Sobrevivente,Classe,Nome,Sexo,Irmaos ou conjuge,Pais ou filhos,Local de embarque,Ticket,Tarifa do passageiro,Cabine
0,892,0,1,Cristiane,feminino,1,1,Cherbourg,121A,8000,C85

In [ ]:
df.shape

(892, 12)

In [ ]:
def is_dataframe_grande(df: pd.DataFrame):
  total_de_colunas = df.shape[1]
  print(df.shape)
  print(f'O total de colunas do dataframe é: {total_de_colunas}')

  if total_de_colunas > 15:
    print(f'Dataframe grande')
  else:
    print(f'Dataframe pequeno')

df.head(5)

is_dataframe_grande(df)

(892, 12)
O total de colunas do dataframe é: 12
Dataframe pequeno

In [ ]:
def size_linhas(df: pd.DataFrame):
  total_de_linhas = df.shape[0]
  print(f'O total de linhas do dataframe é: {total_de_linhas}')

  if total_de_linhas > 100:
    print(f'Dataframe grande')
  else:
    print(f'Dataframe pequeno')

size_linhas(df)

size_linhas(df.head(5))

O total de linhas do dataframe é: 892
Dataframe grande
O total de linhas do dataframe é: 5
Dataframe pequeno

In [ ]:
df.rename(columns={'Id do passageiro':'id_passageiro".', 'Pais ou filhos' : 'pais_ou_filhos', 'Tarifa do passageiro': 'Tarifa', 'Local de embarque' : 'embarque'})
df.columns = [col.lower() for col in df.columns]
df.columns

Index(['id do passageiro', 'sobrevivente', 'classe', 'nome', 'sexo', 'idade',
       'irmaos ou conjuge', 'pais ou filhos', 'ticket', 'tarifa do passageiro',
       'cabine', 'local de embarque'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 892 entries, 0 to 891
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id do passageiro      892 non-null    int64
 1   sobrevivente          892 non-null    int64
 2   classe                892 non-null    int64
 3   nome                  892 non-null    object
 4   sexo                  892 non-null    object
 5   idade                 714 non-null    float64
 6   irmaos ou conjuge     892 non-null    int64
 7   pais ou filhos        892 non-null    int64
 8   ticket                892 non-null    object
 9   tarifa do passageiro  892 non-null    object
 10  cabine                205 non-null    object
 11  local de embarque     890 non-null    object
dtypes: float64(1), int64(5), object(6)
memory usage: 83.8+ KB

In [ ]:
df.dtypes

id do passageiro          int64
sobrevivente              int64
classe                    int64
nome                     object
sexo                     object
idade                   float64
irmaos ou conjuge         int64
pais ou filhos            int64
ticket                   object
tarifa do passageiro     object
cabine                   object
local de embarque        object
dtype: object

In [ ]:
data = {
'prova_1': [6,7,8,8,9,3,6],
'prova_2': [7,8,5,7,10,8,7],
'nome': ['Ana', 'Pedro', 'João', 'Carla', 'Silvio','Teresa', 'Claudia'],
'turma':['A','A','B','B','A','B','B']
}
df2 = pd.DataFrame(data)
df2

   prova_1  prova_2     nome turma
0        6        7      Ana     A
1        7        8    Pedro     A
2        8        5     João     B
3        8        7    Carla     B
4        9       10   Silvio     A
5        3        8   Teresa     B
6        6        7  Claudia     B

In [ ]:
df.describe()

,id do passageiro,sobrevivente,classe,idade,irmaos ou conjuge,pais ou filhos
count,892.000000,892.000000,892.000000,714.000000,892.000000,892.000000
mean,446.500000,0.383408,2.307175,29.699118,0.523543,0.382287
std,257.642517,0.486489,0.836750,14.526497,1.102240,0.805871
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000
25%,223.750000,0.000000,2.000000,20.125000,0.000000,0.000000
50%,446.500000,0.000000,3.000000,28.000000,0.000000,0.000000
75%,669.250000,1.000000,3.000000,38.000000,1.000000,0.000000
max,892.000000,1.000000,3.000000,80.000000,8.000000,6.000000

In [ ]:
media_de_idade = df['idade'].mean()
media_de_idade

np.float64(29.69911764705882)

In [ ]:
passageiro_mais_velho = df[df['idade'] >= df['idade'].max()]
passageiro_mais_velho

,id do passageiro,sobrevivente,classe,nome,sexo,idade,irmaos ou conjuge,pais ou filhos,ticket,tarifa do passageiro,cabine,local de embarque
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",masculino,80.0,0,0,27042,30,A23,S

In [ ]:
print(len(df))

892

In [ ]:
classe = df['classe'].value_counts().sort_index(ascending=True)
classe

classe
1    217
2    184
3    491
Name: count, dtype: int64

In [ ]:
df2 = pd.DataFrame([{'nome':'Cristiane', 'turma':'A', 'prova 1': 5, 'prova 2':7}])
df2
df_prova = pd.concat([df_prova1, df2], axis=0, ignore_index=True)
df_prova

In [ ]:
df_titanic.columns
df_titanic.shape
len(df_titanic)

In [ ]:
df_titanic.shape

In [ ]:
df_titanic.dtypes

In [ ]:
len(df_titanic)

In [ ]:
df2.set_index('nome', inplace=True)

In [ ]:
df2.loc[:, 'prova_1']

nome
Ana        6
Pedro      7
João       8
Carla      8
Silvio     9
Teresa     3
Claudia    6
Name: prova_1, dtype: int64

In [ ]:
df2.iloc[1, 0]

np.int64(7)

In [ ]:
df2.loc['Ana', 'prova_2']

np.int64(7)

In [ ]:
df.loc['Ana', 'prova_1'] = 8

In [ ]:
df.loc['Ana', 'prova_1']

np.float64(8.0)

In [ ]:
df.loc['Silvio', 'prova_1'] = 10

In [ ]:
df.loc['Silvio', 'prova_1']

np.float64(10.0)

In [ ]:
df2.loc[["Carla", "Silvio", "Teresa"], 'prova_1']

nome
Carla     8
Silvio    9
Teresa    3
Name: prova_1, dtype: int64

In [ ]:
df2.loc["Carla":"Teresa", "prova_1"]

nome
Carla     8
Silvio    9
Teresa    3
Name: prova_1, dtype: int64

In [ ]:
df2["media"] = (df2['prova_1'] + df2['prova_2'])/2

In [ ]:
df2

         prova_1  prova_2 turma  media
nome
Ana            6        7     A    6.5
Pedro          7        8     A    7.5
João           8        5     B    6.5
Carla          8        7     B    7.5
Silvio         9       10     A    9.5
Teresa         3        8     B    5.5
Claudia        6        7     B    6.5

In [ ]:
filtro = (df2['turma'] == "A")
print(filtro)

nome
Ana         True
Pedro       True
João       False
Carla      False
Silvio      True
Teresa     False
Claudia    False
Name: turma, dtype: bool

In [ ]:
df2['turma'].loc[df2['turma'] =="B"]
print(filtro)

nome
Ana         True
Pedro       True
João       False
Carla      False
Silvio      True
Teresa     False
Claudia    False
Name: turma, dtype: bool

In [ ]:
numero_sobreviventes = len(df[df['sobrevivente'] ==1])
numero_sobreviventes
tripulantes = len(df)

porcentagem_sobrevimentes = len(df[df['sobrevivente']==1]) / len(df) * 100


print(f'{porcentagem_sobrevimentes}')

38.25503355704698

In [ ]:
df2[(df2['turma'] == 'B') & ((df2['prova_1'] >= 8) | (df2['prova_2'] >=8))]

        prova_1  prova_2 turma  media
nome
João          8        5     B    6.5
Carla         8        7     B    7.5
Teresa        3        8     B    5.5

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 894 entries, 0 to Silvio
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id do passageiro      892 non-null    float64
 1   sobrevivente          892 non-null    float64
 2   classe                892 non-null    float64
 3   nome                  892 non-null    object
 4   sexo                  892 non-null    object
 5   idade                 714 non-null    float64
 6   irmaos ou conjuge     892 non-null    float64
 7   pais ou filhos        892 non-null    float64
 8   ticket                892 non-null    object
 9   tarifa do passageiro  892 non-null    object
 10  cabine                205 non-null    object
 11  local de embarque     890 non-null    object
 12  prova_1               2 non-null      float64
dtypes: float64(7), object(6)
memory usage: 130.1+ KB

In [ ]:
sobreviventes_homens = df[(df['sexo'] == 'masculino') & df['sobrevivente'] == 1]
len(sobreviventes_homens)

109

In [ ]:
df['sexo'].value_counts()

sexo
masculino    577
feminino     315
Name: count, dtype: int64

In [ ]:
sobreviventes_feminino = df[(df['sexo'] == 'feminino') & (df['sobrevivente'] == 1)]
len(sobreviventes_feminino)

233

In [ ]:
filhos = df[(df['idade'] >= 40) & (df['pais ou filhos'] >= 0)]
total_filhos = len(filhos)

print(f'O total de pessoas com mais de 40 anos e com filhos {total_filhos}')

O total de pessoas com mais de 40 anos e com filhos 163

In [ ]:
sobreviveu_c1_c2 = df[(df['sobrevivente'] == 1) & ((df['classe'] == 1) | (df['classe'] == 2))]
sobreviventes = len(sobreviveu_c1_c2)

print(f'A quantidade de sobreviventes da classe 1 e classe 2 é: {sobreviventes}')

A quantidade de sobreviventes da classe 1 e classe 2 é: 223

In [ ]:
df[df['idade'].isnull()].head(5)
df_titanic_filter = df.copy()

In [ ]:
df_titanic_filter ['idade'].fillna(0, inplace=True)
df_titanic_filter[df_titanic_filter['idade'] == 0].head(5)

/tmp/ipykernel_12426/3332848920.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_titanic_filter ['idade'].fillna(0, inplace=True)

,id do passageiro,sobrevivente,classe,nome,sexo,idade,irmaos ou conjuge,pais ou filhos,ticket,tarifa do passageiro,cabine,local de embarque,prova_1
5,6.0,0.0,3.0,"Moran, Mr. James",masculino,0.0,0.0,0.0,330877,8.4583,NaN,Queenstown,NaN
17,18.0,1.0,2.0,"Williams, Mr. Charles Eugene",masculino,0.0,0.0,0.0,244373,13,NaN,S,NaN
19,20.0,1.0,3.0,"Masselmani, Mrs. Fatima",feminino,0.0,0.0,0.0,2649,7.225,NaN,C,NaN
26,27.0,0.0,3.0,"Emir, Mr. Farred Chehab",masculino,0.0,0.0,0.0,2631,7.225,NaN,C,NaN
28,29.0,1.0,3.0,"O'Dwyer, Miss. Ellen ""Nellie""",feminino,0.0,0.0,0.0,330959,7.8792,NaN,Q,NaN

In [ ]:
df['idade'].mean()

np.float64(29.69911764705882)

In [ ]:
df_titanic_filter['idade'].mean()

np.float64(23.71942953020134)

In [ ]:
df_titanic_filter = df_titanic_filter.dropna(subset=['local de embarque'])
df_titanic_filter

,id do passageiro,sobrevivente,classe,nome,sexo,idade,irmaos ou conjuge,pais ou filhos,ticket,tarifa do passageiro,cabine,local de embarque,prova_1
0,1.0,0.0,3.0,"Braund, Mr. Owen Harris",masculino,22.0,1.0,0.0,A/5 21171,7.25,NaN,Southampton,NaN
1,2.0,1.0,1.0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",feminino,38.0,1.0,0.0,PC 17599,712.833,C85,Cherbourg,NaN
2,3.0,1.0,3.0,"Heikkinen, Miss. Laina",feminino,26.0,0.0,0.0,STON/O2. 3101282,7.925,NaN,Southampton,NaN
3,4.0,1.0,1.0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",feminino,35.0,1.0,0.0,113803,53.1,C123,Southampton,NaN
4,5.0,0.0,3.0,"Allen, Mr. William Henry",masculino,35.0,0.0,0.0,373450,08.05,NaN,Southampton,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
887,888.0,1.0,1.0,"Graham, Miss. Margaret Edith",feminino,19.0,0.0,0.0,112053,30,B42,S,NaN
888,889.0,0.0,3.0,"Johnston, Miss. Catherine Helen ""Carrie""",feminino,0.0,1.0,2.0,W./C. 6607,23.45,NaN,S,NaN
889,890.0,1.0,1.0,"Behr, Mr. Karl Howell",masculino,26.0,0.0,0.0,111369,30,C148,C,NaN
890,891.0,0.0,3.0,"Dooley, Mr. Patrick",masculino,32.0,0.0,0.0,370376,7.75,NaN,Q,NaN
891,892.0,0.0,1.0,Cristiane,feminino,0.0,1.0,1.0,121A,8000,C85,Cherbourg,NaN

In [ ]:
df_titanic_filter = df_titanic_filter.drop(2)
df_titanic_filter.head(5)

,id do passageiro,sobrevivente,classe,nome,sexo,idade,irmaos ou conjuge,pais ou filhos,ticket,tarifa do passageiro,cabine,local de embarque,prova_1
0,1.0,0.0,3.0,"Braund, Mr. Owen Harris",masculino,22.0,1.0,0.0,A/5 21171,7.25,NaN,Southampton,NaN
1,2.0,1.0,1.0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",feminino,38.0,1.0,0.0,PC 17599,712.833,C85,Cherbourg,NaN
3,4.0,1.0,1.0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",feminino,35.0,1.0,0.0,113803,53.1,C123,Southampton,NaN
4,5.0,0.0,3.0,"Allen, Mr. William Henry",masculino,35.0,0.0,0.0,373450,08.05,NaN,Southampton,NaN
5,6.0,0.0,3.0,"Moran, Mr. James",masculino,0.0,0.0,0.0,330877,8.4583,NaN,Queenstown,NaN

In [ ]:
df_titanic_idade = df_titanic_filter.drop(columns=['idade'])
df_titanic_idade.info()

<class 'pandas.core.frame.DataFrame'>
Index: 889 entries, 0 to 891
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id do passageiro      889 non-null    float64
 1   sobrevivente          889 non-null    float64
 2   classe                889 non-null    float64
 3   nome                  889 non-null    object
 4   sexo                  889 non-null    object
 5   irmaos ou conjuge     889 non-null    float64
 6   pais ou filhos        889 non-null    float64
 7   ticket                889 non-null    object
 8   tarifa do passageiro  889 non-null    object
 9   cabine                203 non-null    object
 10  local de embarque     889 non-null    object
 11  prova_1               0 non-null      float64
dtypes: float64(6), object(6)
memory usage: 122.6+ KB